### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by SqueeG** [SqueeG/awesomeTome#18]
I was under the impression that third parties were allowed to copywrite their content like WotC does with their boxing-off-of-their-copyrights.

**Comment by Tarkisflux** [comment]
Let's start with standard "I Am Not A Lawyer" disclaimers. That said...

Yes, and no. Derivative work including modification, improvement, addition, modification, and correction seem to be covered by the license by default, and accepting the license to reprint material means accepting it for those things as well. So any simple fixes that use even a bit of the original text need to be released under the same. Which covers most of what we've discussed doing so far. Larger changes like the weapons and armor are sort of gray area, but we might as well OGL them for ass covering purposes. New classes and spells and systems (like the edge mechanic) probably don't need to be included under the OGL though, if we wanted to piecemeal things out in the legal include.

**Comment by SqueeG** [comment]
Yea. The classes and stuff are basically what I was talking about. I'd prefer to 'protect' those by default if possible.

**Comment by Lokathor** [comment]
A work released under the OGL has two licenses. The OGL, which is applied to all content declared to be Open Game Content. This is the content that other authors can copy and remix with other Open Game Content and make their own things from, under the terms of the OGL (which includes having to add citations to each thing they referenced in their "section 15" copyright listing).

Other content, any content that isn't Open Game Content, exists under whatever other license the author wants. So you might or might not be able to use it, usually you can't use it. This is why you can use the text of the PHB chapters but not the artwork, for example. The artwork is "Product Identity", and you can't use it freely.

We could declare some or all of our work to be Product Identity, and in fact we would have to if we plan to use Creative Commons artwork from flickr or something like that, because the terms of Creative Commons aren't the same as the terms of the OGL.

We don't _have_ to release any new content generated by us as Open Game Content, actually we could release the entire SRD unmodified and call it all Product Identity within our work and force people to use the Section 15 citations to go and figure out for themselves what they can use by reading the things cited; but we probably should release as much of what we do as open content as possible.

**Comment by Tarkisflux** [comment]
There are plenty of published books that have a "this book contains no OGL material" clause in them that don't make references to product identity, so I don't think we even need to go that route. We could just declare everything but appendices with new content to be OGL, and then license the appendices as whatever we wanted. But I agree that open content is the way to go. Any restrictions on that are not going to be defended in a court of law by our budget of 0 dollars, so there's basically no point in it.

**Comment by SqueeG** [comment]
Eh, I know it's probably negligible but I just don't like the idea of the larger companies being able to reprint shit willy nilly.

I know it's very tinfoil hat, especially since it'll.probably just be rpg-community people ever copying stuff, but even token 'protection' of a fan's work is worth it. I just didn't quite understand how the whole thing worked.

**Comment by Lokathor** [comment]
By saying that "this book contains no OGL material" they are saying that all material within the book is being categorized as Product Identity.

If a company DID choose to reprint our shit, they'd need to include our Section 15 copyright statement, which would include our names in it. So you'd be able to just open up the book and point to your name and say "I had a hand in this" and it'd be cool.

You can never (legally) remove entries from the Section 15 of an OGL thing, you just keep adding them in every time you stick more OGL into a thing, or derive a new work, and it just keeps piling up credits of who did what when... forever.

**Comment by Tarkisflux** [comment]
Don't they have to call it out as product identity @Lokathor when they do that, rather than just the blanket "no OGL" statement?

And yes, your name will forever be reprinted along with these changes @SqueeG. If you wanted to do otherwise, you'd need something like the CC-BY-SA-NC 3 for the section (to allow distribution and copies and modifications but not selling for profits).

**Comment by SqueeG** [comment]
That... makes much more sense. Thanks. :P

**Comment by Lokathor** [comment]
> Don't they have to call it out as product identity @Lokathor when they do that, rather than just the blanket "no OGL" statement?

Kinda. Open Game Content seems to be the default state of anything in a work that's licensed under the OGL. Then you declare what your Product Identity is.

D) "Open Game Content" means the game mechanic and includes the methods, procedures, processes and routines to the extent such content does not embody the Product Identity and is an enhancement over the prior art and any additional content clearly identified as Open Game Content by the Contributor, _and means any work covered by this License, including translations and derivative works under copyright law, but specifically excludes Product Identity._
E) "Product Identity" means product and product line names, logos and identifying marks including trade dress; artifacts; creatures characters; stories, storylines, plots, thematic elements, dialogue, incidents, language, artwork, symbols, designs, depictions, likenesses, formats, poses, concepts, themes and graphic, photographic and other visual or audio representations; names and descriptions of characters, spells, enchantments, personalities, teams, personas, likenesses and special abilities; places, locations, environments, creatures, equipment, magical or supernatural abilities or effects, logos, symbols, or graphic designs; _and any other trademark or registered trademark clearly identified as Product identity by the owner of the Product Identity, and which specifically excludes the Open Game Content;_
